"""initial schema

Revision ID: 5c44fff4f8cb
Revises: 
Create Date: 2026-06-09 11:42:37.710875
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5c44fff4f8cb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('download_url', sa.String(length=800), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('minimum_supported_version', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', 'channel', name='uq_agent_version_channel')
    )
    op.create_table('security_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('device_id', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('guest', 'end_user', 'developer', 'team_member', 'team_admin', 'platform_admin', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('agent_update_channels',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('active_version_id', sa.String(length=40), nullable=True),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['agent_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token_prefix'), ['token_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.String(length=40), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=48), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('team_id', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_team_id'), ['team_id'], unique=False)

    op.create_table('developer_profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('org_name', sa.String(length=160), nullable=False),
    sa.Column('support_email', sa.String(length=320), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('accepted_terms_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('device_flows',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_code', sa.String(length=16), nullable=False),
    sa.Column('device_code_hash', sa.String(length=128), nullable=False),
    sa.Column('approved_user_id', sa.String(length=40), nullable=True),
    sa.Column('device_id', sa.String(length=40), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_flows_device_code_hash'), ['device_code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_flows_user_code'), ['user_code'], unique=True)

    op.create_table('devices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('anonymous_device_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('agent_version', sa.String(length=16), nullable=False),
    sa.Column('os', sa.Enum('windows', 'macos', 'linux', 'unknown', name='device_os', native_enum=False), nullable=False),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('agent_public_key_b64', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_anonymous_device_id'), ['anonymous_device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('release.validated', 'release.validation_failed', 'release.published', 'high_failure_rate', 'rollout.paused', 'rollback.done', 'install_link.used', 'new_login', 'team.changed', 'api_token.created', name='notification_kind', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('recovery_codes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_codes_user_id'), ['user_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)

    op.create_table('two_factor_secrets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('replaced_by_id', sa.String(length=40), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('os', sa.Enum('windows', 'macos', 'linux', 'unknown', name='session_os', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=True)
        batch_op.create_index('ix_user_sessions_user_active', ['user_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('device_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_description', sa.String(length=280), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('privacy_policy_url', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'private', name='project_visibility', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'suspended', 'archived', 'deleted', name='project_status', native_enum=False), nullable=False),
    sa.Column('owner_user_id', sa.String(length=40), nullable=False),
    sa.Column('team_id', sa.String(length=40), nullable=True),
    sa.Column('extension_id', sa.String(length=32), nullable=True),
    sa.Column('allow_channel_switch', sa.Boolean(), nullable=False),
    sa.Column('bridge_mode', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_extension_id'), ['extension_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_team_id'), ['team_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('team_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'developer', 'release_manager', 'admin', name='team_role', native_enum=False), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('install_links',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('token', sa.String(length=96), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('link_type', sa.Enum('public', 'private_secret', 'one_time', 'expiring', 'usage_limited', 'channel_scoped', 'requires_account', 'email_domain', 'org_scoped', name='install_link_type', native_enum=False), nullable=False),
    sa.Column('channel', sa.Enum('stable', 'beta', 'nightly', name='install_link_channel', native_enum=False), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('requires_account', sa.Boolean(), nullable=False),
    sa.Column('allowed_email_domain', sa.String(length=255), nullable=True),
    sa.Column('org_team_id', sa.String(length=40), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('install_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_install_links_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_install_links_token'), ['token'], unique=True)

    op.create_table('project_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('public_key_b64', sa.Text(), nullable=False),
    sa.Column('private_key_encrypted', sa.Text(), nullable=False),
    sa.Column('extension_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    with op.batch_alter_table('project_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_keys_extension_id'), ['extension_id'], unique=False)

    op.create_table('releases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('stable', 'beta', 'nightly', name='release_channel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'validating', 'validation_failed', 'ready', 'draft', 'scheduled', 'publishing', 'published', 'paused', 'superseded', 'revoked', name='release_status', native_enum=False), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=40), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('minimum_agent_version', sa.String(length=16), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('permissions_changed', sa.Boolean(), nullable=False),
    sa.Column('requires_user_approval', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('signed_metadata', sa.JSON(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('key_id', sa.String(length=64), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('superseded_by_release_id', sa.String(length=40), nullable=True),
    sa.Column('version_lock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_release_project_sequence'),
    sa.UniqueConstraint('project_id', 'version', 'channel', name='uq_release_version_channel')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_releases_status'), ['status'], unique=False)

    op.create_table('rollout_assignments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.Enum('stable', 'beta', 'nightly', name='rollout_channel', native_enum=False), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('bucket', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'channel', 'device_id', name='uq_rollout_assignment')
    )
    with op.batch_alter_table('rollout_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollout_assignments_project_id'), ['project_id'], unique=False)

    op.create_table('webhooks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_project_id'), ['project_id'], unique=False)

    op.create_table('channel_assignments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.Enum('stable', 'beta', 'nightly', name='channel_assign', native_enum=False), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('assigned_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_assignments_project_id'), ['project_id'], unique=False)

    op.create_table('channels',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.Enum('stable', 'beta', 'nightly', name='channel_state', native_enum=False), nullable=False),
    sa.Column('active_release_id', sa.String(length=40), nullable=True),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['active_release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'channel', name='uq_channel_project')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_project_id'), ['project_id'], unique=False)

    op.create_table('installations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.Enum('stable', 'beta', 'nightly', name='installation_channel', native_enum=False), nullable=False),
    sa.Column('current_release_id', sa.String(length=40), nullable=True),
    sa.Column('current_version', sa.String(length=32), nullable=True),
    sa.Column('extension_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('downloading', 'staged', 'awaiting_manual_load', 'installed', 'update_available', 'updating', 'reload_required', 'up_to_date', 'paused', 'broken', 'rollback_in_progress', 'removed', name='installation_status', native_enum=False), nullable=False),
    sa.Column('has_bridge', sa.Boolean(), nullable=False),
    sa.Column('updates_paused', sa.Boolean(), nullable=False),
    sa.Column('install_link_id', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'project_id', name='uq_installation_device_project')
    )
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installations_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installations_status'), ['status'], unique=False)

    op.create_table('release_artifacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('s3_bucket', sa.String(length=120), nullable=False),
    sa.Column('s3_key', sa.String(length=400), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_artifacts_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('release_permission_snapshots',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('optional_permissions', sa.JSON(), nullable=False),
    sa.Column('host_permissions', sa.JSON(), nullable=False),
    sa.Column('optional_host_permissions', sa.JSON(), nullable=False),
    sa.Column('content_scripts_matches', sa.JSON(), nullable=False),
    sa.Column('externally_connectable', sa.JSON(), nullable=True),
    sa.Column('uses_native_messaging', sa.Boolean(), nullable=False),
    sa.Column('web_accessible_resources', sa.JSON(), nullable=False),
    sa.Column('diff_added', sa.JSON(), nullable=True),
    sa.Column('diff_removed', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('release_id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('webhook_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('installation_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('installation_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_events_installation_id'), ['installation_id'], unique=False)

    op.create_table('update_attempts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('installation_id', sa.String(length=40), nullable=False),
    sa.Column('release_id', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('from_version', sa.String(length=32), nullable=True),
    sa.Column('to_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'downloading', 'verifying', 'applying', 'awaiting_reload', 'success', 'failed', 'rolled_back', name='update_attempt_status', native_enum=False), nullable=False),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('reload_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'idempotency_key', name='uq_update_attempt_idem')
    )
    with op.batch_alter_table('update_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update_attempts_installation_id'), ['installation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_update_attempts_release_id'), ['release_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update_attempts_release_id'))
        batch_op.drop_index(batch_op.f('ix_update_attempts_installation_id'))

    op.drop_table('update_attempts')
    with op.batch_alter_table('installation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_events_installation_id'))

    op.drop_table('installation_events')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_webhook_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_next_retry_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event_id'))

    op.drop_table('webhook_deliveries')
    op.drop_table('release_permission_snapshots')
    with op.batch_alter_table('release_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_release_artifacts_release_id'))

    op.drop_table('release_artifacts')
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installations_status'))
        batch_op.drop_index(batch_op.f('ix_installations_project_id'))
        batch_op.drop_index(batch_op.f('ix_installations_device_id'))

    op.drop_table('installations')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_project_id'))

    op.drop_table('channels')
    with op.batch_alter_table('channel_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_assignments_project_id'))

    op.drop_table('channel_assignments')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_project_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('rollout_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollout_assignments_project_id'))

    op.drop_table('rollout_assignments')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_status'))
        batch_op.drop_index(batch_op.f('ix_releases_project_id'))

    op.drop_table('releases')
    with op.batch_alter_table('project_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_keys_extension_id'))

    op.drop_table('project_keys')
    with op.batch_alter_table('install_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_install_links_token'))
        batch_op.drop_index(batch_op.f('ix_install_links_project_id'))

    op.drop_table('install_links')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_team_id'))
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_extension_id'))

    op.drop_table('projects')
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_device_sessions_device_id'))

    op.drop_table('device_sessions')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index('ix_user_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token_hash'))

    op.drop_table('user_sessions')
    op.drop_table('two_factor_secrets')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_slug'))

    op.drop_table('teams')
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_codes_user_id'))

    op.drop_table('recovery_codes')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))

    op.drop_table('password_resets')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token_hash'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_devices_anonymous_device_id'))

    op.drop_table('devices')
    with op.batch_alter_table('device_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_flows_user_code'))
        batch_op.drop_index(batch_op.f('ix_device_flows_device_code_hash'))

    op.drop_table('device_flows')
    op.drop_table('developer_profiles')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_team_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_prefix'))

    op.drop_table('api_tokens')
    op.drop_table('agent_update_channels')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_device_id'))

    op.drop_table('security_events')
    op.drop_table('agent_versions')
    # ### end Alembic commands ###
