/** Standalone, dependency-free ExtSync Bridge vendored by `extsync init`.
 * Mirrors packages/extension-bridge but as a single classic/ESM file so it can
 * be dropped into any extension. It never downloads or runs remote code. */

const CORE = String.raw`
var EXTSYNC_PROTOCOL = 1;
var EXTSYNC_HOST = "com.extsync.agent";
function extsyncInit(opts) {
  var listeners = {};
  var port = null, connected = false, pendingNonce = null;
  function on(ev, cb){ (listeners[ev]=listeners[ev]||[]).push(cb); }
  function emit(ev, d){ (listeners[ev]||[]).forEach(function(cb){ try{cb(d);}catch(e){} }); }
  function send(type, payload, reqId){
    if(!port) return;
    try{ port.postMessage({protocolVersion:EXTSYNC_PROTOCOL,requestId:reqId||("req_"+Date.now()),
      timestamp:Date.now(),projectId:opts.projectId,extensionId:chrome.runtime.id,type:type,payload:payload}); }
    catch(e){ disconnect(); }
  }
  function disconnect(){ connected=false; port=null; emit("agentDisconnected",{lastError:(chrome.runtime.lastError||{}).message}); }
  function onMessage(m){
    if(!m||typeof m!=="object"||m.protocolVersion!==EXTSYNC_PROTOCOL) return;
    if(m.projectId && m.projectId!==opts.projectId) return;
    if(m.type==="update.reload_ready"){
      var nonce=(m.payload||{}).nonce; if(!nonce) return;
      pendingNonce=nonce; emit("reloadRequested",{nonce});
      send("update.reload_ack",{nonce},m.requestId);
      emit("updateCompleted",{version:(m.payload||{}).version});
      if(opts.autoReload!==false) chrome.runtime.reload();
    } else if(m.type==="update.failed"){ emit("updateFailed",m.payload); }
    else if(m.type==="agent.status"){ emit("agentConnected",m.payload); }
  }
  function connect(){
    try{ port=chrome.runtime.connectNative(EXTSYNC_HOST); }
    catch(e){ disconnect(); return; }
    port.onMessage.addListener(onMessage);
    port.onDisconnect.addListener(disconnect);
    connected=true; emit("agentConnected");
    send("extension.register",{version:chrome.runtime.getManifest().version,channel:opts.channel});
  }
  Promise.resolve().then(connect);
  return {
    onAgentConnected:function(cb){on("agentConnected",cb);},
    onAgentDisconnected:function(cb){on("agentDisconnected",cb);},
    onUpdatePrepared:function(cb){on("updatePrepared",cb);},
    onReloadRequested:function(cb){on("reloadRequested",cb);},
    onUpdateCompleted:function(cb){on("updateCompleted",cb);},
    onUpdateFailed:function(cb){on("updateFailed",cb);},
    reload:function(n){ if(!n||n===pendingNonce) chrome.runtime.reload(); },
    reportStatus:function(s,d){ send(s==="success"?"update.success":"update.failed", Object.assign({version:chrome.runtime.getManifest().version}, d||{})); }
  };
}
`;

export const CLASSIC_BRIDGE_JS =
  "// ExtSync Bridge (classic). Generated by `extsync init`. Do not edit.\n" +
  CORE +
  "\nself.initializeExtSync = extsyncInit;\n";

export const MODULE_BRIDGE_JS =
  "// ExtSync Bridge (ES module). Generated by `extsync init`. Do not edit.\n" +
  CORE +
  "\nexport const initializeExtSync = extsyncInit;\n";

export function classicSnippet(): string {
  return [
    'importScripts("extsync-bridge.js");',
    'self.initializeExtSync({ projectId: "REPLACE_PROJECT_ID", channel: "stable" });',
  ].join("\n");
}

export function moduleSnippet(): string {
  return [
    'import { initializeExtSync } from "./extsync-bridge.mjs";',
    'initializeExtSync({ projectId: "REPLACE_PROJECT_ID", channel: "stable" });',
  ].join("\n");
}
